{{- if .Values.developerMode.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "xapp_core.fullname" . }}-xapp-ssh
  labels:
    {{- include "xapp_core.labels" . | nindent 4 }}
    drax/xapp-component-name: xapp-dev-ssh
spec:
  type: {{ .Values.sshService.type }}
  ports:
    - port: {{ .Values.sshService.port }}
      name:  {{ .Values.sshService.name }}
      {{ if .Values.sshService.nodePort }}
      nodePort: {{ .Values.sshService.nodePort }}
      {{ end }}
  selector:
    {{- include "xapp_core.selectorLabels" . | nindent 4 }}
{{- end }}
