apiVersion: v2
name: cell-wrapper
description: Accelleran Cell Wrapper Components
type: application
# UPDATE .global.topChart.version IN VALUES FILE TO MATCH!
version: 2.2.0
appVersion: "CW2.2.0"
dependencies:
  - name: acc-common
    version: 0.2.0
    repository: https://accelleran.github.io/helm-charts-ng/
  - name: netconf
    condition: netconf.enabled
    version: 3.0.0
    repository: https://accelleran.github.io/helm-charts-ng/
