apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "acc-common.fullname" . }}-instance-scaler
data:
  config.yaml: |
    subscribers:
    - kind: "nats"
      topic: "{{ include "acc-common.drax.instanceId" . }}.INSTANCE-SCALER"
      host: "{{ .Values.global.nats.hostname }}"
      port: {{ .Values.global.nats.port }}

    instances:
    - id: "{{ include "acc-common.drax.instanceId" . }}/cw-inst"
      kind: "deployment"
      namespace: "{{ .Release.Namespace }}"
      name: "{{ .Release.Name }}-cw-inst"
      spare: {{ .Values.cw-inst.spareInstanceCount }}
