{{- if and (.Values.initEditConfig.enabled) (gt (len .Values.initEditConfig.config) 0) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "acc-common.fullname" . }}-netconf-init-rpcs
  labels:
    {{- include "acc-common.labels.5g" . | nindent 4 }}
data:

  {{- range $index, $configRpc := .Values.initEditConfig.config }}
  init-edit-config-{{- $index -}}.xml: |
    {{- tpl $configRpc $ | nindent 4 }}
  {{- end }}
{{- end }}
