apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-cw-ctrl
  labels:
    {{- include "acc-common.labels.5g" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "acc-common.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.cw-ctrl.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "acc-common.labels.5g" . | nindent 8 }}
    spec:
      {{- with .Values.cw-ctrl.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: "{{ include "acc-common.fullname" . }}-controller"
      
      volumes:
      - name: {{ include "acc-common.fullname" . }}-instance-scaler
        configMap:
          name: {{ include "acc-common.fullname" . }}-instance-scaler

      {{- if .Values.cw-ctrl.global.config.enabled }}
      initContainers:
        - name: wait-for-netconf-init-config
          image: ghcr.io/groundnuty/k8s-wait-for:v1.7 # k8s <v1.23
          imagePullPolicy: {{ .Values.cw-ctrl.image.pullPolicy }}
          args:
            - "job"
            - "{{ .Release.Name }}-netconf-init-config"
          securityContext:
            {{- toYaml .Values.cw-ctrl.securityContext | nindent 12 }}
      {{- end }}
      containers:
        - name: cw-ctrl
          image: "{{ .Values.cw-ctrl.image.repository }}:{{ tpl .Values.cw-ctrl.image.tag . | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.cw-ctrl.image.pullPolicy }}

          env:
            - name: __APPNAME
              value: cellWrapperController
            {{- with .Values.cw-ctrl.env.extra }}
            {{ toYaml . | nindent 12 }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: "{{ include "cell-wrapper.bootstrap.configMapName" .Values.cw-ctrl }}"

          {{- with .Values.cw-ctrl.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.cw-ctrl.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}

        - name: instance-scaler
          image: "{{ .Values.instance-scaler.image.repository }}:{{ tpl .Values.instance-scaler.image.tag . | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.instance-scaler.image.pullPolicy }}
          volumeMounts:
          - name: {{ include "acc-common.fullname" . }}-instance-scaler
            mountPath: /config.yaml
            subPath: config.yaml
            readOnly: true

          {{- with .Values.instance-scaler.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.instance-scaler.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}

      {{- with .Values.cw-ctrl.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- if or (.Values.cw-ctrl.nodeSelector) (eq (tpl .Values.cw-ctrl.draxNodeSelectorEnabled .) "true") }}
      nodeSelector:
        {{ if .Values.cw-ctrl.nodeSelector }}
          {{- toYaml .Values.cw-ctrl.nodeSelector | nindent 8 }}
        {{ end }}
        {{ if eq (tpl .Values.cw-ctrl.draxNodeSelectorEnabled .) "true" }}
          {{- tpl (toYaml .Values.cw-ctrl.draxNodeSelector) $ | nindent 8 }}
        {{ end }}
      {{- end }}

      {{- with .Values.cw-ctrl.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.cw-ctrl.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
