{
 "title": "5G CUCP PM Counters",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "InstanceID",
    "query": "label_values(RRC_CONNECTION_EST_ATTEMPT_total,instanceId)"
   },
   {
    "name": "instanceType",
    "query": "label_values(RRC_CONNECTION_EST_ATTEMPT_total,instanceType)"
   },
   { "name": "MinStep", "query": "1m,5m,10m,30m,1h" },
   {
    "name": "sliceType",
    "query": "label_values(DRB_PACKET_LOSS_UL_SNSSAI,sst)"
   },
   {
    "name": "sliceDifferentiator",
    "query": "label_values(DRB_PACKET_LOSS_UL_SNSSAI,sd)"
   }
  ]
 },
 "panels": [
  {
   "title": "RRC Connection Success Rate [%]",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "increase(RRC_CONNECTION_SUCC_total {instanceId=~\"$InstanceID\",instanceType=~\"$instanceType\"} [$__rate_interval]) * 100 / increase(RRC_CONNECTION_EST_ATTEMPT_total {instanceId=~\"$InstanceID\",instanceType=~\"$instanceType\"}[$__rate_interval])",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 5 },
   "options": {
    "content": "<h4 style=\"text-align:center\"> <h4>\n<h4 style=\"text-align:center\"> <h4>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "RRC CONNECTION EST ATTEMPTS ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(RRC_CONNECTION_EST_ATTEMPT_total {instanceId=~\"$InstanceID\",instanceType=~\"$instanceType\"}[$__range])))\n",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "title": "increase(RRC CONNECTION ESTABLISHMENT ATTEMPTS)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(RRC_CONNECTION_EST_ATTEMPT_total {instanceId=~\"$InstanceID\",instanceType=~\"$instanceType\"}[$__rate_interval])",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "EMERGENCY",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(RRC_CONN_EST_ATT_CAUSE_TYPE_EMERGENCY_total {instanceId=~\"$InstanceID\",instanceType=~\"$instanceType\"}[$__range])))\n",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "title": "MT_ACCESS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(RRC_CONN_EST_ATT_CAUSE_TYPE_MT_ACCESS_total {instanceId=~\"$InstanceID\",instanceType=~\"$instanceType\"}[$__range])))\n",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "title": "MO_DATA",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " round(sum(increase(RRC_CONN_EST_ATT_CAUSE_TYPE_MO_DATA_total {instanceId=~\"$InstanceID\",instanceType=~\"$instanceType\"}[$__range])))\n",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "title": "MO_VIDEO_CALL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " round(sum(increase(RRC_CONN_EST_ATT_CAUSE_TYPE_MO_VIDEO_CALL_total {instanceId=~\"$InstanceID\",instanceType=~\"$instanceType\"}[$__range])))\n",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "title": "MPS_PRIORITY_ACCESS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(RRC_CONN_EST_ATT_CAUSE_TYPE_MPS_PRIORITY_ACCESS_total {instanceId=~\"$InstanceID\",instanceType=~\"$instanceType\"}[$__range])))\n",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "HIGH_PRIORITY_ACCESS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(RRC_CONN_EST_ATT_CAUSE_TYPE_HIGH_PRIORITY_ACCESS_total {instanceId=~\"$InstanceID\",instanceType=~\"$instanceType\"}[$__range])))\n",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "title": "MO_SIGNALLING",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(RRC_CONN_EST_ATT_CAUSE_TYPE_MO_SIGNALLING_total {instanceId=~\"$InstanceID\",instanceType=~\"$instanceType\"}[$__range])))\n",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "title": "MO_VOICE_CALL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " round(sum(increase(RRC_CONN_EST_ATT_CAUSE_TYPE_MO_VOICE_CALL_total {instanceId=~\"$InstanceID\",instanceType=~\"$instanceType\"}[$__range])))\n",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "title": "MO_SMS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "  round(sum(increase(RRC_CONN_EST_ATT_CAUSE_TYPE_MO_SMS_total {instanceId=~\"$InstanceID\",instanceType=~\"$instanceType\"}[$__range])))\n",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "title": "MCS_PRIORITY_ACCESS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(RRC_CONN_EST_ATT_CAUSE_TYPE_MCS_PRIORITY_ACCESS_total {instanceId=~\"$InstanceID\",instanceType=~\"$instanceType\"}[$__range])))\n",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 17 },
   "options": {
    "content": "<h4 style=\"text-align:center\">RRC_CONNECTION_EST_ATTEMPT <h4>\n<h4 style=\"text-align:center\"> cause sub-counters <h4>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 20 },
   "options": {
    "content": "<h4 style=\"text-align:center\"> <h4>\n<h4 style=\"text-align:center\"> <h4>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "RRC CONNECTION SUCCESSES",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " round(sum(increase(RRC_CONNECTION_SUCC_total {instanceId=~\"$InstanceID\",instanceType=~\"$instanceType\"}[$__range])))\n",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "title": "increase(RRC CONNECTION SUCCESSES) ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(RRC_CONNECTION_SUCC_total {instanceId=~\"$InstanceID\",instanceType=~\"$instanceType\"}[$__rate_interval])",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "EMERGENCY",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(RRC_CONNECTION_SUCC_CAUSE_TYPE_EMERGENCY_total {instanceId=~\"$InstanceID\",instanceType=~\"$instanceType\"}[$__range])))\n",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "title": "MT_ACCESS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(RRC_CONNECTION_SUCC_CAUSE_TYPE_MT_ACCESS_total {instanceId=~\"$InstanceID\",instanceType=~\"$instanceType\"}[$__range])))\n",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "title": "MO_DATA",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(RRC_CONNECTION_SUCC_CAUSE_TYPE_MO_DATA_total {instanceId=~\"$InstanceID\",instanceType=~\"$instanceType\"}[$__range])))\n",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "title": "MO_VIDEO_CALL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(RRC_CONNECTION_SUCC_CAUSE_TYPE_MO_VIDEO_CALL_total {instanceId=~\"$InstanceID\",instanceType=~\"$instanceType\"}[$__range])))\n",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "title": "MPS_PRIORITY_ACCESS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " round(sum(increase(RRC_CONNECTION_SUCC_CAUSE_TYPE_MPS_PRIORITY_ACCESS_total {instanceId=~\"$InstanceID\",instanceType=~\"$instanceType\"}[$__range])))\n",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 30 },
   "options": {
    "content": "<h4 style=\"text-align:center\">RRC_CONNECTION_SUCCESS <h4>\n<h4 style=\"text-align:center\"> cause sub-counters <h4>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "HIGH_PRIORITY_ACCESS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(RRC_CONNECTION_SUCC_CAUSE_TYPE_HIGH_PRIORITY_ACCESS_total {instanceId=~\"$InstanceID\",instanceType=~\"$instanceType\"}[$__range])))\n",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "title": "MO_SIGNALLING",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(RRC_CONNECTION_SUCC_CAUSE_TYPE_MO_SIGNALLING_total {instanceId=~\"$InstanceID\",instanceType=~\"$instanceType\"}[$__range])))\n",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "title": "MO_VOICE_CALL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(RRC_CONNECTION_SUCC_CAUSE_TYPE_MO_VOICE_CALL_total {instanceId=~\"$InstanceID\",instanceType=~\"$instanceType\"}[$__range])))\n",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "title": "MO_SMS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " round(sum(increase(RRC_CONNECTION_SUCC_CAUSE_TYPE_MO_SMS_total {instanceId=~\"$InstanceID\",instanceType=~\"$instanceType\"}[$__range])))\n",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "title": "MCS_PRIORITY_ACCESS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(RRC_CONNECTION_SUCC_CAUSE_TYPE_MCS_PRIORITY_ACCESS_total {instanceId=~\"$InstanceID\",instanceType=~\"$instanceType\"}[$__range])))\n",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 34 },
   "options": {
    "content": "<h4 style=\"text-align:center\"> <h4>\n<h4 style=\"text-align:center\"> <h4>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "MEAN NUMBER OF RRC CONNECTIONS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(MEAN_NUMBER_OF_RRC_CONNECTIONS {instanceId=~\"$InstanceID\",instanceType=~\"$instanceType\"}[$__interval])",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "title": "MAX NUMBER OF RRC CONNECTIONS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 5, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(MAXIMUM_NUMBER_OF_RRC_CONNECTIONS {instanceId=~\"$InstanceID\",instanceType=~\"$instanceType\"}[$__interval])",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "title": "PDU SESSION SETUP REQUESTS",
   "type": "stat",
   "description": "Number of PDU sessions requested to setup (28.522 section 5.1.1.5.1). CU-CP counter per NR cell. The measurement is split into subcounters per S-NSSAI\n\n",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(NUMBER_OF_PDU_SESSIONS_REQUESTED_TO_SETUP_total {instanceId=~\"$InstanceID\",instanceType=~\"$instanceType\"}[$__range])))",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "title": "PDU SESSION SETUP FAILURES",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(NUMBER_OF_PDU_SESSIONS_FAILED_TO_SETUP_total {instanceId=~\"$InstanceID\",instanceType=~\"$instanceType\"}[$__range])))",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 41 },
   "options": {
    "content": "<h4 style=\"text-align:center\"> <h4>\n<h4 style=\"text-align:center\"> <h4>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "INTRA GNB HANDOVER EXECUTIONS",
   "type": "stat",
   "description": "Intra gNB counter incremented at both intra and inter DU handover. Incremented by one at sending of RRC Reconfiguration message to initiate the handover in the UE",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " round(sum(increase(REQ_INTRA_GNB_HANDOVER_EXECUTIONS_total {instanceId=~\"$InstanceID\",instanceType=~\"$instanceType\"}[$__range])))\n",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "title": "INTRA GNB Handover Success Rate [%]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "increase(SUCC_INTRA_GNB_HANDOVER_EXECUTIONS_total {instanceId=~\"$InstanceID\",instanceType=~\"$instanceType\"} [$__rate_interval]) * 100 / increase(REQ_INTRA_GNB_HANDOVER_EXECUTIONS_total {instanceId=~\"$InstanceID\",instanceType=~\"$instanceType\"}[$__rate_interval])",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "title": "INTRA GNB HANDOVER SUCCESSES",
   "type": "stat",
   "description": "Intra gNB counter incremented at both intra and inter DU handover. Incremented by one on reception of RRC Reconfiguration Complete",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " round(sum(increase(SUCC_INTRA_GNB_HANDOVER_EXECUTIONS_total {instanceId=~\"$InstanceID\",instanceType=~\"$instanceType\"}[$__range])))\n",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 52 },
   "targets": [
    {}
   ]
  }
 ]
}