{
 "title": "5G UE Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "UE",
    "query": "SELECT \"ueId\" FROM (SELECT \"ueId\",\"measurement.ssbRsrp\" FROM \"uemeasurement.vector\" WHERE $timeFilter )"
   },
   {
    "name": "Cell",
    "query": "SELECT \"nrCellId\" FROM (SELECT \"nrCellId\",\"measurement.ssbRsrp\" FROM \"uemeasurement.vector\" WHERE $timeFilter )"
   }
  ]
 },
 "panels": [
  {
   "title": "DL Throughput per UE (NG-U interface)",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "ueId: $tag_ueId",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "ueId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uemeasurement.vector",
     "query": "SELECT mean(\"measurement.dlGtpThp\") *8 FROM \"uemeasurement.vector\" WHERE (\"ueId\" =~ /^$UE$/) AND $timeFilter GROUP BY time(1s), \"/^$UE$/\" fill(null)",
     "select": [
      [
       { "params": [ "measurement.dlGtpThroughput" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ueId", "operator": "=~", "value": "/^$UE$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Number of UEs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "default.ssbRsrp",
     "query": "SELECT count(distinct(\"ueId\")) FROM (select * from \"uemeasurement.vector\" WHERE (\"nrCellId\" =~ /^$Cell$/) and time> now()-1m)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "cellId", "operator": "=~", "value": "/^$Cell$/" }
     ]
    }
   ]
  },
  {
   "title": "SSB RSRP",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "alias": "nrCellId: $tag_nrCellId",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "nrCellId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uemeasurement.vector",
     "query": "SELECT (mean(\"measurement.ssbRsrp\") -157) FROM \"uemeasurement.vector\" WHERE (\"nrCellId\" =~ /^$Cell$/ AND \"ueId\" =~ /^$UE$/) AND $timeFilter GROUP BY time(1s), \"nrCellId\" fill(null)",
     "select": [
      [
       { "params": [ "measurement.ssbRsrp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nrCellId", "operator": "=~", "value": "/^$Cell$/" },
      { "condition": "AND", "key": "ueId", "operator": "=~", "value": "/^$UE$/" }
     ]
    }
   ]
  },
  {
   "title": "UL Throughput per UE (NG-U interface)",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "ueId: $tag_ueId",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "ueId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uemeasurement.vector",
     "select": [
      [
       { "params": [ "measurement.ulGtpThroughput" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ueId", "operator": "=~", "value": "/^$UE$/" }
     ]
    }
   ]
  },
  {
   "title": "SSB RSRQ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "alias": "nrcellId: $tag_nrCellId",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "nrCellId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uemeasurement.vector",
     "query": "SELECT (mean(\"measurement.ssbRsrq\")/2-43) FROM \"uemeasurement.vector\" WHERE (\"nrCellId\" =~ /^$Cell$/ AND \"ueId\" =~ /^$UE$/) AND $timeFilter GROUP BY time(1s), \"nrCellId\" fill(null)",
     "select": [
      [
       { "params": [ "measurement.ssbRsrq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nrCellId", "operator": "=~", "value": "/^$Cell$/" },
      { "condition": "AND", "key": "ueId", "operator": "=~", "value": "/^$UE$/" }
     ]
    }
   ]
  },
  {
   "title": "SSB SINR",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "alias": "nrcellId: $tag_nrCellId",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "nrCellId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uemeasurement.vector",
     "query": "SELECT (mean(\"measurement.ssbSinr\")/2-23 )FROM \"uemeasurement.vector\" WHERE (\"nrCellId\" =~ /^$Cell$/ AND \"ueId\" =~ /^$UE$/) AND $timeFilter GROUP BY time(1s), \"nrCellId\" fill(null)",
     "select": [
      [
       { "params": [ "measurement.ssbSinr" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nrCellId", "operator": "=~", "value": "/^$Cell$/" },
      { "condition": "AND", "key": "ueId", "operator": "=~", "value": "/^$UE$/" }
     ]
    }
   ]
  },
  {
   "title": "UE Radio Overview",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "nrCellId: $tag_nrCellId",
     "groupBy": [
      { "params": [ "ueId" ], "type": "tag" },
      { "params": [ "nrCellId" ], "type": "tag" }
     ],
     "measurement": "uemeasurement.vector",
     "query": "SELECT \"measurement.ssbRsrp\" -157 as \"SSB RSRP\",\"measurement.ssbRsrq\"/2-43  as \"SSB RSRQ\", \"measurement.ssbSinr\"/2-23 as \"SSB SINR\"  FROM \"uemeasurement.vector\" WHERE (\"nrCellId\" =~ /^$Cell$/) AND $timeFilter GROUP BY \"ueId\", \"nrCellId\" ORDER BY time DESC  LIMIT 1\n",
     "select": [
      [
       { "params": [ "measurement.ssbRsrp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "nrCellId", "operator": "=~", "value": "/^$Cell$/" }
     ]
    }
   ]
  }
 ]
}