{
 "title": "Kafka Cluster Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Brokers Online",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_server_replicamanager_total_leadercount_value{job=\"kubernetes-service-endpoints\"})"
    }
   ]
  },
  {
   "title": "Active controllers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_controller_kafkacontroller_activecontrollercount_value{job=\"kubernetes-service-endpoints\"})"
    }
   ]
  },
  {
   "title": "Global Partition Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_globalpartitioncount_value{job=\"kafkaMonitoringJmx\"}"
    }
   ]
  },
  {
   "title": "Cluster avg msg/sec",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(kafka_server_brokertopicmetrics_total_messagesinpersec_oneminuterate{job!=\"kafkaMonitoringJmx\"}))"
    }
   ]
  },
  {
   "title": "Messages In Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum by(topic)(kafka_server_brokertopicmetrics_messagesinpersec_oneminuterate{topic!=\"__consumer_offsets\"}))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Consumer group offset",
   "type": "timeseries",
   "description": "Current offset of a given group on a given partition.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (topic_name, group) (rate(kminion_kafka_consumer_group_topic_offset_sum[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Subscribed Consumer Groups",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "kminion_kafka_consumer_group_topic_partition_lag"
    }
   ]
  },
  {
   "title": "Consumer group topic lag",
   "type": "timeseries",
   "description": "Number of commited offset entries by a consumer group for a given partition. Helpful to determine the commit rate to possibly tune the consumer performance.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (group,topic_name) (kminion_kafka_consumer_group_topic_partition_lag)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Performance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(kafka_server_kafkaserver_total_linux_disk_read_bytes_value{job=\"kafkaMonitoringJmx\"}[$__range])",
     "legendFormat": "Disk Read"
    },
    {
     "expr": "rate(kafka_server_kafkaserver_total_linux_disk_write_bytes_value{job=\"kafkaMonitoringJmx\"}[$__range])",
     "legendFormat": "Disk Write"
    }
   ]
  },
  {
   "title": "Bytes In Per Topic",
   "type": "timeseries",
   "description": "Generally, disk throughput tends to be the main bottleneck in Kafka performance. However, that’s not to say that the network is never a bottleneck. Depending on your use case, hardware, and configuration, the network can quickly become the slowest segment of a message’s trip, especially if you are sending messages across data centers. Tracking network throughput on your brokers gives you more information as to where potential bottlenecks may lie, and can inform decisions like whether or not you should enable end-to-end compression of your messages.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum without(instance)(increase(kafka_server_brokertopicmetrics_bytesinpersec_count{topic!=\"__consumer_offsets\"}[$__range]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Topic",
   "type": "timeseries",
   "description": "Generally, disk throughput tends to be the main bottleneck in Kafka performance. However, that’s not to say that the network is never a bottleneck. Depending on your use case, hardware, and configuration, the network can quickly become the slowest segment of a message’s trip, especially if you are sending messages across data centers. Tracking network throughput on your brokers gives you more information as to where potential bottlenecks may lie, and can inform decisions like whether or not you should enable end-to-end compression of your messages.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum without(instance)(increase(kafka_server_brokertopicmetrics_bytesoutpersec_count{topic!=\"__consumer_offsets\"}[$__range]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Producer Purgatory Requests Waiting",
   "type": "timeseries",
   "description": "Number of requests waiting in the producer purgatory. This should be non-zero when acks=all is used on the producer.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_server_delayedoperationpurgatory_numdelayedoperations_remotefetch_value{job=\"kafkaMonitoringJmx\"}",
     "legendFormat": "RemoteFetch"
    },
    {
     "expr": "kafka_server_delayedoperationpurgatory_numdelayedoperations_electleader_value{job=\"kafkaMonitoringJmx\"}",
     "legendFormat": "ElectLeader"
    },
    {
     "expr": "kafka_server_delayedoperationpurgatory_numdelayedoperations_produce_value{job=\"kafkaMonitoringJmx\"}",
     "legendFormat": "Produce"
    },
    {
     "expr": "kafka_server_delayedoperationpurgatory_numdelayedoperations_fetch_value{job=\"kafkaMonitoringJmx\"}",
     "legendFormat": "Fetch"
    },
    {
     "expr": "kafka_server_delayedoperationpurgatory_numdelayedoperations_deleterecords_value{job=\"kafkaMonitoringJmx\"}",
     "legendFormat": "DeleteRecords"
    },
    {
     "expr": "kafka_server_delayedoperationpurgatory_numdelayedoperations_heartbeat_value{job=\"kafkaMonitoringJmx\"}",
     "legendFormat": "Heartbeat"
    },
    {
     "expr": "kafka_server_delayedoperationpurgatory_numdelayedoperations_alteracls_value{job=\"kafkaMonitoringJmx\"}",
     "legendFormat": "AlterAcls"
    },
    {
     "expr": "kafka_server_delayedoperationpurgatory_numdelayedoperations_rebalance_value{job=\"kafkaMonitoringJmx\"}",
     "legendFormat": "Rebalance"
    }
   ]
  },
  {
   "title": "Total Time Ms",
   "type": "timeseries",
   "description": "Total time (in ms) to serve the specified request (Produce/Fetch)",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " sum(kafka_network_requestmetrics_totaltimems_count) by(request)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Produce request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_totalproducerequestspersec_oneminuterate{job=\"kafkaMonitoringJmx\",topic!=\"__consumer_offsets\"}[$__range])",
     "legendFormat": "{{ topic }}"
    }
   ]
  },
  {
   "title": "Fetch request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_totalfetchrequestspersec_oneminuterate{job=\"kafkaMonitoringJmx\",topic!=\"__consumer_offsets\"}[$__range])",
     "legendFormat": "{{ topic }}"
    }
   ]
  }
 ]
}