{
 "title": "Loki Log Dashboard",
 "description": "Loki logs panel with prometheus variables ",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "Node",
    "query": "label_values(kubernetes_io_hostname)"
   },
   {
    "name": "Pod",
    "query": "label_values(kube_pod_info{node=~\"^$Node$\"}, pod)"
   },
   {
    "name": "Container",
    "query": "label_values(kube_pod_container_info{pod=\"$Pod\"}, container)"
   },
   { "name": "Pod_Container_Search" },
   { "name": "External_Source_Search" }
  ]
 },
 "panels": [
  {
   "title": "Instructions",
   "type": "text",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "\n# Instructions\nWe show two Log panels and their accompamying filtering options on the top:\n- The left \"Pod/Container Logs\" - For which you have the following available filters: namespace, Node, Pod, Container, Pod/Container_Search\n- The right \"External Source Logs\" - For which you have one available filters: External_Source, External_Source_Search\n\nThe \"Pod/Container_Search\" can be used to filter for custom text in the \"Pod/Container Logs\" panel.\nThe \"External_Source_Search\" can be used to filter for custom text in the \"External Source Logs\" panel.\nThe \"Log Timeline\" can be used to filter based on date and time for both Logs Panels.\n\nIf you want to view one of the Log Panel full screen, you can left click on the Log Panel title and select \"View\" from the drop-down menu.\n\n\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Log timeline",
   "type": "graph",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", instance=~\"$Pod\", node=~\"$Node\", container=~\"$Container\"} |~ \"$Pod_Container_Search\"[$__interval]))"
    },
    {
     "expr": "sum(count_over_time({source=~\"$External_Source\"} |~ \"$External_Source_Search\"[$__interval]))"
    }
   ]
  },
  {
   "title": "Pod/Container Logs ",
   "type": "logs",
   "gridPos": { "h": 24, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\", instance=~\"$Pod\", node=~\"$Node\", container=~\"$Container\"} |~ \"$Pod_Container_Search\" "
    }
   ]
  },
  {
   "title": "External Source Logs",
   "type": "logs",
   "gridPos": { "h": 24, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "{source=~\"$External_Source\"} |~ \"$External_Source_Search\" "
    }
   ]
  }
 ]
}